compressionLevel: mixed

nodeLinker: node-modules

packageExtensions:
  "@commitlint/load@*":
    dependencies:
      "@types/node": "*"
  "@digitalroute/cz-conventional-changelog-for-jira@*":
    dependencies:
      "@types/node": "*"
      ts-node: "*"
      typescript: "*"
  "@nrwl/devkit@*":
    dependencies:
      typescript: "*"
  "@nrwl/eslint-plugin-nx@*":
    dependencies:
      eslint: "*"
      nx: 15.4.4
  "@nrwl/js@*":
    dependencies:
      nx: 15.4.4
      tslib: "*"
  "@nrwl/linter@*":
    dependencies:
      nx: 15.4.4
      typescript: "*"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
