packageExtensions:
  "@commitlint/load@*":
    dependencies:
      "@types/node": "*"
  "@digitalroute/cz-conventional-changelog-for-jira@*":
    dependencies:
      "@types/node": "*"
      ts-node: "*"
      typescript: "*"
  "@nrwl/devkit@*":
    dependencies:
      typescript: "*"
  "@nrwl/js@*":
    dependencies:
      nx: 15.4.4
      tslib: "*"
  "@nrwl/linter@*":
    dependencies:
      nx: 15.4.4
      typescript: "*"
  "@nrwl/eslint-plugin-nx@*":
    dependencies:
      eslint: "*"
      nx: 15.4.4

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
